modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/auioc/HarmonicEnchantments/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
updateJSONURL = "https://hi.auioc.org/HarmonicEnchantments/update/1.20.4.json"
displayURL = "http://hi.auioc.org/HarmonicEnchantments/"
logoFile = "icon.png"
credits = "${mod_credits}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId = "arnicalib"
    type="required"
    versionRange = "${arnicalib_version_range}"
    ordering = "NONE"
    side = "BOTH"
