# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: dev-build

on:
    push:
        branches-ignore:
            - 'test*'
        tags-ignore:
            - 'v*'

jobs:
    build:
        name: Build
        if: ${{ !startsWith(github.event.head_commit.message, 'release') }}
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4

            -   name: Set up JDK 17
                uses: actions/setup-java@v4
                with:
                    java-version: '17'
                    distribution: 'temurin'
                    architecture: 'x64'
                    cache: 'gradle'

            -   name: Build with Gradle
                run: |
                    chmod +x ./gradlew
                    ./gradlew runData
                    ./gradlew build
                    echo "ARTIFACT_NAME=`cat ./build/tmp/artifact-name.txt`" >> $GITHUB_ENV

            -   name: Upload build artifacts
                uses: actions/upload-artifact@v1
                with:
                    name: ${{env.ARTIFACT_NAME}}
                    path: build/libs
